version: "3.9"

services:

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  payment:
    container_name: payment
    build: .
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - redis