version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  payment-bot:
    container_name: payment-api
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data